# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transact_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
