# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_auto_20170912_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
