# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20170913_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
