# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20170913_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
