# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 02:58
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_auto_20170915_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
