# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0013_auto_20170915_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
