# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('price', '0017_transaction_balance_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=250)),
                ('bought_shares', models.IntegerField(default=0)),
                ('sold_shares', models.IntegerField(default=0)),
                ('bal_shares', models.IntegerField(default=0)),
                ('current_market_price', models.FloatField(default=0.0)),
                ('market_evaluation', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
